package com.gmail.kamiloleksik.jfxkonwerter.keys;

public enum NamesKey
{
	MAIN_WINDOW_UNIT_NAMES, PREFERENCES_UNIT_NAMES, ALL_UNIT_TYPE_NAMES, APP_LANGUAGES_NAMES, UNITS_LANGUAGES_NAMES,
	APP_SKINS_NAMES, ALLOWED_NUMBERS_OF_DECIMAL_PLACES
}