package com.gmail.kamiloleksik.jfxkonwerter.util.keys;

public enum DaoKey
{
	UNIT_TYPE_DAO, UNIT_TYPE_EN_DAO, UNIT_DAO, UNIT_EN_DAO, UNITS_LANGUAGE_DAO, APP_LANGUAGE_DAO, PREFERENCES_DAO,
	NUMBER_OF_DECIMAL_PLACES_DAO, APP_SKIN_DAO
}